- hosts: confluence
  become: true

  vars:
    os_user: yangyuchi
    confluence_bin_path: /home/yangyuchi/confluence_bin
    setenv_url: https://gist.githubusercontent.com/marsyang1/02b9ebd050b5778cc4f66a3447aaace9/raw/c0d2ce07f36833fe6926e994f649970c771003e1/setenv.sh
    confluence_home_path: /home/yangyuchi/confluence_home
    xmx_size: 3900
    confluence_db_name: confluence
    confluence_db_user: confluence
    confluence_db_password: confluence

  tasks:
    - name: ==> 1 create confluence_home folder
      file: path={{ confluence_home_path }} owner={{ os_user }} group={{ os_user }} state=directory mode=0777

    - name: ==> 2 create confluence_bin folder
      file: path={{ confluence_bin_path }} owner={{ os_user }} group={{ os_user }} state=directory mode=0777

    - name: ==> 3 download confluence setenv.sh
      get_url: url={{ setenv_url }} dest={{ confluence_bin_path }}/setenv.sh mode=0775

    - name: adjust max memory
      replace: dest={{ confluence_bin_path }}/setenv.sh regexp="-Xms1024m -Xmx1024m" replace="-Xms1024m -Xmx{{ xmx_size }}m"

    - name: ==> 4 run docker confluence
      docker_container:
        name: confluence
        image: cptactionhank/atlassian-confluence
        restart_policy: always
        ports:
          - "80:8090"
        volumes:
          - "{{ confluence_home_path }}:/var/atlassian/confluence"
          - "{{ confluence_bin_path }}/setenv.sh:/opt/atlassian/confluence/bin/setenv.sh"
