# host usually use all , sometime and apply to some server role
# but also can use ansible-playbook with --limit , more dynamicly
- hosts: all
  # sudo permission
  become: true

  vars:
    hostname: mywordpress

  tasks:
    - name: ==> 0 - add host info
      # equals enhance sec , http://docs.ansible.com/ansible/lineinfile_module.html
      lineinfile: dest=/etc/hosts line="10.0.0.10  {{ hostname }}" state=present

