Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.network "private_network", ip: "10.0.0.10"
  #config.vm.network "forwarded_port", guest: 80, host: 8080

  # use vagrant and ansible integration plugin to use more easy
  # vagrant will auto create inventory file at  $VagrantFolder$0/.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory 
  config.vm.provision "ansible" do |ansible|
     ansible.playbook = "setup.yml"
     ansible.sudo = true
  end

end
