Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"

  config.vm.network "private_network", ip: "10.0.0.200"

  config.vm.provision "ansible" do |ansible|
     ansible.playbook = "setup.yml"
     ansible.sudo = true
  end

end
